version : "3"
services:
  db:
    container_name: cnusam-db
    image: mysql
    environment:
      MYSQL_DATABASE: cnusam
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
    restart: always
  cache:
    container_name: cnusam-cache
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
  app:
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: cnusam-app
    ports:
      - "8080:8080"
    working_dir: /app
    depends_on:
      - db
      - cache
    restart: always
    environment:
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
      SPRING_DATASOURCE_URL: jdbc:mysql://cnusam-db:3306/cnusam?serverTimezone=UTC
      SPRING_DATASOURCE_DRIVERCLASSNAME: com.mysql.cj.jdbc.Driver