/*OSS_LICENSE_TYPE*/
INSERT INTO oss_license_type (license_type_name) VALUES ('Copyleft');
INSERT INTO oss_license_type (license_type_name) VALUES ('Permissive');
INSERT INTO oss_license_type (license_type_name) VALUES ('Proprietary');
INSERT INTO oss_license_type (license_type_name) VALUES ('Proprietary Free');
INSERT INTO oss_license_type (license_type_name) VALUES ('Weak Copyleft');

/*PROJECT_CATEGORY*/
INSERT INTO PROJECT_CATEGORY (PROJECT_CATEGORY_NAME) VALUES ('개인');
INSERT INTO PROJECT_CATEGORY (PROJECT_CATEGORY_NAME) VALUES ('기타');
INSERT INTO PROJECT_CATEGORY (PROJECT_CATEGORY_NAME) VALUES ('대회');
INSERT INTO PROJECT_CATEGORY (PROJECT_CATEGORY_NAME) VALUES ('수업');
INSERT INTO PROJECT_CATEGORY (PROJECT_CATEGORY_NAME) VALUES ('연구');
INSERT INTO PROJECT_CATEGORY (PROJECT_CATEGORY_NAME) VALUES ('졸업');
INSERT INTO PROJECT_CATEGORY (PROJECT_CATEGORY_NAME) VALUES ('창업');

/*RESTRICTION*/
INSERT INTO RESTRICTION (RESTRICTION_NAME) VALUES ('배포시 라이선스사본첨부');
INSERT INTO RESTRICTION (RESTRICTION_NAME) VALUES ('조합저작물 작성 및 타 라이선스 배포허용');
INSERT INTO RESTRICTION (RESTRICTION_NAME) VALUES ('저작권 고지사항 또는 Attribution 고지사항 유지');
INSERT INTO RESTRICTION (RESTRICTION_NAME) VALUES ('수정내용 고지');
INSERT INTO RESTRICTION (RESTRICTION_NAME) VALUES ('명시적 특허라이선스의 허용');
INSERT INTO RESTRICTION (RESTRICTION_NAME) VALUES ('이름, 상표, 상호에 대한 사용제한');
INSERT INTO RESTRICTION (RESTRICTION_NAME) VALUES ('보증의 부인');
INSERT INTO RESTRICTION (RESTRICTION_NAME) VALUES ('책임의 제한');