/*OSS_LICENSE_TYPE*/
INSERT INTO oss_license_type (license_type_name) VALUES ('Copyleft');
INSERT INTO oss_license_type (license_type_name) VALUES ('Permissive');
INSERT INTO oss_license_type (license_type_name) VALUES ('Proprietary');
INSERT INTO oss_license_type (license_type_name) VALUES ('Proprietary Free');
INSERT INTO oss_license_type (license_type_name) VALUES ('Weak Copyleft');

/*PROJECT_CATEGORY*/
INSERT INTO PROJECT_CATEGORY (PROJECT_CATEGORY_NAME) VALUES ('개인');
INSERT INTO PROJECT_CATEGORY (PROJECT_CATEGORY_NAME) VALUES ('기타');
INSERT INTO PROJECT_CATEGORY (PROJECT_CATEGORY_NAME) VALUES ('대회');
INSERT INTO PROJECT_CATEGORY (PROJECT_CATEGORY_NAME) VALUES ('수업');
INSERT INTO PROJECT_CATEGORY (PROJECT_CATEGORY_NAME) VALUES ('연구');
INSERT INTO PROJECT_CATEGORY (PROJECT_CATEGORY_NAME) VALUES ('졸업');
INSERT INTO PROJECT_CATEGORY (PROJECT_CATEGORY_NAME) VALUES ('창업');

/*RESTRICTION*/
INSERT INTO RESTRICTION (RESTRICTION_NAME) VALUES ('배포시 라이선스사본첨부');
INSERT INTO RESTRICTION (RESTRICTION_NAME) VALUES ('조합저작물 작성 및 타 라이선스 배포허용');
INSERT INTO RESTRICTION (RESTRICTION_NAME) VALUES ('저작권 고지사항 또는 Attribution 고지사항 유지');
INSERT INTO RESTRICTION (RESTRICTION_NAME) VALUES ('수정내용 고지');
INSERT INTO RESTRICTION (RESTRICTION_NAME) VALUES ('명시적 특허라이선스의 허용');
INSERT INTO RESTRICTION (RESTRICTION_NAME) VALUES ('이름, 상표, 상호에 대한 사용제한');
INSERT INTO RESTRICTION (RESTRICTION_NAME) VALUES ('보증의 부인');
INSERT INTO RESTRICTION (RESTRICTION_NAME) VALUES ('책임의 제한');

/*LECTURE_TYPE*/
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('교양');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('교양필수');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('교양선택');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('교양일반');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('교양공통기초');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('교양핵심');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('교양전문기초');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('전공');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('전공필수');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('전공선택');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('전공기초');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('전공핵심');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('전공심화');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('교직');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('기초');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('기초필수');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('기초선택');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('기초공통');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('일반선택');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('공통');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('선수');
INSERT INTO LECTURETYPE (LECTURETYPE) VALUES ('미기재');

/*DEPARTMENT*/
INSERT INTO DEPARTMENT (DEPARTMENT) VALUES ('학부');
INSERT INTO DEPARTMENT (DEPARTMENT) VALUES ('일반대학원');
INSERT INTO DEPARTMENT (DEPARTMENT) VALUES ('법학전문대학원');
INSERT INTO DEPARTMENT (DEPARTMENT) VALUES ('의학전분대학원');
INSERT INTO DEPARTMENT (DEPARTMENT) VALUES ('분석과학기술대학원');
INSERT INTO DEPARTMENT (DEPARTMENT) VALUES ('에너지과학기술대학원');
INSERT INTO DEPARTMENT (DEPARTMENT) VALUES ('신약전문대학원');
INSERT INTO DEPARTMENT (DEPARTMENT) VALUES ('녹색에너지기술전문대학원');
INSERT INTO DEPARTMENT (DEPARTMENT) VALUES ('경영대학원');
INSERT INTO DEPARTMENT (DEPARTMENT) VALUES ('교육대학원');
INSERT INTO DEPARTMENT (DEPARTMENT) VALUES ('행정대학원');
INSERT INTO DEPARTMENT (DEPARTMENT) VALUES ('보건대학원');
INSERT INTO DEPARTMENT (DEPARTMENT) VALUES ('산업대학원');
INSERT INTO DEPARTMENT (DEPARTMENT) VALUES ('특허법무대학원');
INSERT INTO DEPARTMENT (DEPARTMENT) VALUES ('평화안보대학원');
INSERT INTO DEPARTMENT (DEPARTMENT) VALUES ('보건·바이오산업기술대학원');
INSERT INTO DEPARTMENT (DEPARTMENT) VALUES ('국가정책대학원');
INSERT INTO DEPARTMENT (DEPARTMENT) VALUES ('스마트농업대학원');
